title = "Animations"
gitRepoUrl = "https://github.com/wrello/Animations"

gitSourceBranch = "master"
changelog = true
classOrder = [
    "AnimationsClient",
    "AnimationsServer",
    "AnimationIds",
    "AutoCustomRBXAnimationIds"
]

[home]
enabled = true
includeReadme = true

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
tagline = "An easy to use module for playing and pre-loading animations"

[[navbar.items]]
href = "https://devforum.roblox.com/t/animations-a-robust-easy-to-use-animation-player-pre-loader/2504740"
label = "Roblox DevForum"
position = "right"

[footer]
style = "dark"
copyright = "Built with Moonwave and Docusaurus"

[[footer.links]]
title = "Links"

[[footer.links.items]]
label = "Support"
href = "https://www.paypal.com/paypalme/isaacpalmr"
